Optional ValidatorsResponse cursor
iotaledger/iota-sdk pull request #1165
Opened 2023-09-07 08:40 UTC by thibault-martinez

https://github.com/iotaledger/tips-draft/pull/24/commits/450b51911994700151b6ab67b19ab43840e5e791

2023-09-07 09:17 UTC, Thoralf-M requested changes
Please also add the optional cursor as parameter https://github.com/iotaledger/tips-draft/pull/24/files#diff-04aff9a5004dd8023df5735c866f69254359635764a00e9d9215500a9676319bR2881-R2883
to `get_validators()`

2023-09-07 14:30 UTC, thibault-martinez commented
> Please also add the optional cursor as parameter https://github.com/iotaledger/tips-draft/pull/24/files#diff-04aff9a5004dd8023df5735c866f69254359635764a00e9d9215500a9676319bR2881-R2883 to `get_validators()`

I had a look and I think I'll do it in another PR. The `query` parameters of `get_request` is not very handy, it forces us to create the param string ourselves. This should take a vector and build the string inside.

2023-09-07 14:32 UTC, Alexandcoats approved these changes

2023-09-07 14:37 UTC, Thoralf-M approved these changes

2023-09-11 11:57 UTC, kwek20 approved these changes

2023-09-11 13:13 UTC, DaughterOfMars approved these changes

2023-09-11 13:35 UTC, Alex6323 approved these changes

2023-09-11 13:36 UTC, merged