Feat/Node: readonly and bigint leftover
iotaledger/iota-sdk pull request #1218
Opened 2023-09-12 16:38 UTC by kwek20

# Description of change

Fixes [#966](https://github.com/iotaledger/iota-sdk/issues/966)

2023-09-12 16:58 UTC, Thoralf-M approved these changes, later dismissed

2023-09-12 18:11 UTC, thibault-martinez requested changes
Format :trollface:

2023-09-12 19:08 UTC, Thoralf-M submitted a review, later dismissed

2023-09-13 07:26 UTC, thibault-martinez commented on bindings/nodejs/lib/types/block/address.ts
> +     * Get the type of address.
I don't know if I would put getter-like comments for fields...

2023-09-13 14:14 UTC, Alex6323 approved these changes

2023-09-13 14:20 UTC, thibault-martinez approved these changes

2023-09-13 20:51 UTC, Alexandcoats approved these changes

2023-09-13 21:34 UTC, Thoralf-M approved these changes

2023-09-14 07:04 UTC, merged