fix
iotaledger/iota-sdk pull request #1253
Opened 2023-09-18 18:23 UTC by kwek20

# Description of change

Transaction payload wasnt parsed due to cyclic dependency in class-transformer.
Setting it to Always being TaggedDataPayload solves this as the discriminator is no longer needed.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota-sdk/issues/1249

2023-09-18 18:48 UTC, Thoralf-M commented
Changelog entry?

2023-09-18 19:02 UTC, kwek20 commented
Erm well technically it always was a TaggedDataPayload, and it never worked before :P but alright

2023-09-18 21:42 UTC, DaughterOfMars approved these changes

2023-09-19 07:12 UTC, Thoralf-M approved these changes

2023-09-19 07:15 UTC, thibault-martinez commented on bindings/nodejs/lib/types/block/payload/transaction/essence.ts
> +        payload: TaggedDataPayload | undefined,
Will this serialize the type?

2023-09-19 11:17 UTC, kwek20 commented on bindings/nodejs/lib/types/block/payload/transaction/essence.ts
> +        payload: TaggedDataPayload | undefined,
Yes, I tested it

2023-09-22 09:00 UTC, msarcev commented
Maybe this can be a temporary fix while we find a better one. At the moment it would be nice to have a fix to unblock the integration in Explorer.

2023-09-22 09:01 UTC, thibault-martinez commented
> Maybe this can be a temporary fix while we find a better one. At the moment it would be nice to have a fix to unblock the integration in Explorer.

Abdul is having another look now and we'll merge it if it's not conclusive.

2023-09-25 09:26 UTC, thibault-martinez requested changes
.

2023-09-25 10:27 UTC, closed without merging