EVM howtos for L1 -> L2 in js/ts
iotaledger/iota-sdk pull request #1383
Opened 2023-10-03 13:56 UTC by anistark

# Description of change

How to guide to send base, native and nft tokens from L1 to L2 in js/ts.

## Links to any relevant issues

Part of [wiki issue #1155](https://github.com/iotaledger/iota-wiki/issues/1155)

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Ran each example.
Running examples are added in each file.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-10-03 19:14 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_base_token_to_evm.ts
> +// yarn run-example ./how_tos/outputs/unlock-conditions.ts
Wrong

2023-10-03 19:15 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_base_token_to_evm.ts
> +    // console.log('amounts:', bigAmount, bigGas);
Remove all the commented console logs if they should not actually be enabled in this example

2023-10-04 09:20 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_nft_to_evm.ts
>          // Basic Output with Metadata
```suggestion
        // NFT Output with Metadata
```

2023-10-04 11:30 UTC, thibault-martinez requested changes
Conflicts

2023-10-04 14:48 UTC, kwek20 requested changes
not sure about this cursor/util thing,we need to find a way to do this using the sdk.
not sure if thats in scope for now tho

2023-10-04 14:48 UTC, kwek20 commented on bindings/nodejs/examples/how_tos/evm/send_base_token_to_evm.ts
> +    const _syncBalance = await account.sync();
_syncBalance and balance are the same, so no need to call it twice. and can also remove the eslint then :)

2023-10-04 14:48 UTC, kwek20 commented on bindings/nodejs/.gitignore
> +.venv-nodejs
whats this about? a python venv? Not sure we need it here tbh

2023-10-04 14:48 UTC, kwek20 commented on bindings/nodejs/examples/how_tos/evm/send_base_token_to_evm.ts
> +    const bigAmount: bigint = BigInt(amount);
no need to define bigint type here

2023-10-04 14:48 UTC, kwek20 commented on bindings/nodejs/examples/how_tos/evm/send_native_token_to_evm.ts
> +    INativeToken,
unused Inative

2023-10-04 17:03 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_native_token_to_evm.ts
> +    const bigAmount: bigint = BigInt(amount);
Type bigint trivially inferred from a bigint literal, remove type annotation

2023-10-04 17:03 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_native_token_to_evm.ts
> +    const bigGas: bigint = BigInt(gas);
Type bigint trivially inferred from a bigint literal, remove type annotation

2023-10-04 17:03 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_nft_to_evm.ts
> +    const bigGas: bigint = BigInt(gas);
Type bigint trivially inferred from a bigint literal, remove type annotation

2023-10-04 17:05 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_nft_to_evm.ts
> +    const client = new Client({});
New Client without node will use default options which might be wrong depending on which network is used
Remove this and just get the client from the wallet instead when needed
`await wallet.getClient()`

2023-10-04 17:05 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
> +  readUInt64LE(): BigInt {
Don't use `BigInt` as a type. Use bigint instead

2023-10-04 17:05 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
> +  writeUInt64SpecialEncoding(value: BigInt): void {
Don't use `BigInt` as a type. Use bigint instead

2023-10-04 17:05 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/utils.ts
> +    for (var bytes = [], c = 0; c < hex.length; c += 2)
Unexpected var, use let or const instead

2023-10-04 17:06 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/utils.ts
> +    // console.log(metadata.buffer.toString('hex'))
```suggestion
```

2023-10-04 17:08 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
Many things aren't even called in the examples, why are they here?

2023-10-05 05:29 UTC, anistark commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
The entire file was in evm-toolkit. Thought can move it all inside sdk sometime rust side once we've a helper function of sorts for this later.

2023-10-23 07:05 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
I think we don't want to put EVM stuff into the SDK itself, apart from address generation and signing for stronghold, this can be done with separated libraries
Would still remove everything that's not actually required and for reference just put a link to the source where you copied at the top

2023-10-24 13:27 UTC, thibault-martinez commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
I agree, we should have the strictly required minimum in the SDK regarding EVM

2023-10-25 09:18 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/send_nft_to_evm.ts
> +        // Ref: https://wiki.iota.org/wasp-evm/reference/core-contracts/evm#registererc20nativetoken
But this is the NFT example

2023-10-25 10:31 UTC, anistark commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
So, should the separate library be something like `@iota/evm-sdk` or should it be a separate external library maintained by community or something?

2023-10-25 12:44 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
Actually you copied it from evm-toolkit, so there is already a library, no?

2023-10-25 14:19 UTC, anistark commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
No. It's a standalone code. And only 1 file is copied. Cause of the functions which are already used there.

2023-10-25 14:19 UTC, anistark commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
Whatever new library is created or added to sdk itself, will then be used both in evm-toolkit and in firefly later.

2023-10-25 14:25 UTC, thibault-martinez commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
What do you mean it's a standalone code ? That it's not published ?

2023-10-26 10:46 UTC, anistark commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
No, I mean it's live but it's not part of any library as such.

2023-10-27 08:26 UTC, thibault-martinez commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
As discussed on Slack, it looks like we won't be adding EVM-related stuff in the SDK. Let's close this PR and when you have a place where to add them, we'll probably also move the already existing examples there.

2023-10-27 10:30 UTC, anistark commented on bindings/nodejs/examples/how_tos/evm/simple-buffer-cursor.ts
Sounds good. Closing it for now.

2023-10-27 10:30 UTC, closed without merging