feat/python: Delegation output fields
iotaledger/iota-sdk pull request #1408
Opened 2023-10-09 13:29 UTC by kwek20

# Description of change

Adds the proper fields in delegation output

## Links to any relevant issues

fixes #1174

2023-10-09 15:06 UTC, Thoralf-M commented on bindings/python/iota_sdk/types/output.py
> +        end_epoch: 	The index of the last epoch for which this output delegates.
```suggestion
        end_epoch: The index of the last epoch for which this output delegates.
```

2023-10-09 15:07 UTC, Thoralf-M commented on bindings/python/iota_sdk/types/output.py
> +    unlock_conditions: List[UnlockCondition]
I think we need ` = field(
        metadata=config(
            decoder=deserialize_unlock_conditions
        ))` here

2023-10-10 11:23 UTC, Thoralf-M approved these changes, later dismissed

2023-10-10 12:35 UTC, DaughterOfMars submitted a review, later dismissed

2023-10-10 14:41 UTC, thibault-martinez requested changes

2023-10-10 14:41 UTC, thibault-martinez commented on bindings/python/iota_sdk/types/output.py
> +    unlock_conditions: List[UnlockCondition] = field(metadata=config(
This should be an union of the only allowed UCs like the other outputs, not the whole union

2023-10-10 14:55 UTC, thibault-martinez approved these changes, later dismissed

2023-10-10 14:57 UTC, DaughterOfMars submitted a review, later dismissed

2023-10-10 15:02 UTC, Thoralf-M approved these changes, later dismissed

2023-10-10 15:38 UTC, Alex6323 approved these changes, later dismissed

2023-10-10 15:53 UTC, DaughterOfMars approved these changes

2023-10-10 15:53 UTC, Alex6323 approved these changes

2023-10-10 15:54 UTC, thibault-martinez approved these changes

2023-10-10 15:55 UTC, Thoralf-M approved these changes

2023-10-11 10:34 UTC, merged