[WIP] patch: check environment variable existence
iotaledger/iota-sdk pull request #1427
Opened 2023-10-13 06:34 UTC by raprocks

# Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #issue_number`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-10-18 17:51 UTC, thibault-martinez commented
Hi @raprocks, thanks for the PR! Just checking in, do you have any question regarding the issue?

2023-10-31 19:12 UTC, thibault-martinez commented
Hi @raprocks, let us know if you don't have time to finish and we'll do it

2023-11-01 21:40 UTC, raprocks commented
hey @thibault-martinez , i got a little busy but i am back now. The PR was not for hacktoberfest haha, i will complete in this week sometime and make this ready for submission. I have the task clear. Thanks

2023-11-18 10:31 UTC, raprocks commented
@thibault-martinez Please Review and let me know if any other changes are necessary

2023-11-18 15:54 UTC, Thoralf-M commented on bindings/nodejs/examples/client/05-get-address-balance.ts
> +
```suggestion
```

2023-11-19 13:27 UTC, thibault-martinez commented on bindings/nodejs/examples/client/05-get-address-balance.ts
L26 of this file, remove the check

2023-11-19 13:30 UTC, thibault-martinez commented on bindings/nodejs/examples/client/09-transaction.ts
L26, remove the check

2023-11-19 13:30 UTC, thibault-martinez commented on bindings/nodejs/examples/client/14-build-foundry-output.ts
L31 remove the check

2023-11-21 08:11 UTC, Thoralf-M commented on bindings/nodejs/examples/client/06-simple-block.ts
> +    for (const envVar of ['NODE_URL']) {
```suggestion
    for (const envVar of ['NODE_URL', 'EXPLORER_URL']) {
```

2023-11-21 11:15 UTC, raprocks commented
sorry missed that!

2023-11-21 12:14 UTC, Thoralf-M requested changes
@raprocks there are some warnings now (you should also see them locall with `yarn lint`), because TS doesn't know the type of the values
I think if you just put `as string` in those places it should be fine again

2023-11-21 13:27 UTC, Thoralf-M approved these changes
Thanks!

2023-11-21 13:55 UTC, thibault-martinez approved these changes
Thank you :)

2023-11-21 13:55 UTC, merged