feat(types): Add delegation to balance
iotaledger/iota-sdk pull request #1456
Opened 2023-10-18 09:00 UTC by Alex6323

## Links to any relevant issues

Closes #1245

2023-10-27 12:50 UTC, thibault-martinez requested changes
Also need to actually use it when computing balances

2023-11-06 13:08 UTC, thibault-martinez commented
Any news on this?

2023-11-07 08:35 UTC, Thoralf-M submitted a review, later dismissed

2023-11-07 13:47 UTC, DaughterOfMars submitted a review, later dismissed

2023-11-13 09:05 UTC, thibault-martinez requested changes
I'd update the bindings as well since the change is super small

2023-11-27 08:54 UTC, Thoralf-M approved these changes, later dismissed

2023-11-27 15:14 UTC, DaughterOfMars approved these changes, later dismissed

2023-11-27 16:08 UTC, DaughterOfMars approved these changes, later dismissed

2023-11-27 16:11 UTC, thibault-martinez submitted a review, later dismissed

2023-11-27 16:12 UTC, Thoralf-M commented on bindings/nodejs/lib/types/wallet/wallet.ts
> +    /** The required amount for Alias outputs. */
```suggestion
    /** The required amount for Account outputs. */
```

2023-11-27 16:13 UTC, thibault-martinez approved these changes

2023-11-27 16:13 UTC, Thoralf-M approved these changes

2023-11-27 16:35 UTC, merged