Add new block failure reasons
iotaledger/iota-sdk pull request #1468
Opened 2023-10-19 12:44 UTC by DaughterOfMars

# Description of change

Adds new block failure reasons from iota.go.

## Links to any relevant issues

Closes #1466

2023-10-19 12:45 UTC, thibault-martinez commented on sdk/src/types/api/core/response.rs
Do we have this enum in nodejs/python as well?

2023-10-19 12:51 UTC, DaughterOfMars commented on sdk/src/types/api/core/response.rs
Apparently not in nodejs, but it is in python

2023-10-19 13:04 UTC, DaughterOfMars commented on sdk/src/types/api/core/response.rs
I added it to both

2023-10-19 15:00 UTC, thibault-martinez commented on bindings/nodejs/lib/types/models/block-metadata.ts
> +    txState?: TransactionState;
This is `transactionState` in the TIP

2023-10-19 15:00 UTC, thibault-martinez commented on bindings/nodejs/lib/types/models/block-metadata.ts
> +    txFailureReason?: TransactionFailureReason;
This is `transactionFailureReason` in the TIP

2023-10-19 15:05 UTC, thibault-martinez commented on bindings/nodejs/lib/types/models/block-metadata.ts
> +    txState?: TransactionState;
Asked on Slack. If ever it changed, needs to be applied to Python as well.

2023-10-19 15:08 UTC, thibault-martinez commented on bindings/nodejs/lib/types/models/block-metadata.ts
> +    blockState?: BlockState;
```suggestion
    blockState: BlockState;
```
Not optional. Can you do the same in Python and remove the TODO please ?

2023-10-19 15:11 UTC, DaughterOfMars commented on bindings/nodejs/lib/types/models/block-metadata.ts
> +    blockState?: BlockState;
sure

2023-10-19 17:26 UTC, thibault-martinez approved these changes

2023-10-19 17:26 UTC, thibault-martinez requested changes
Conflicts

2023-10-19 17:47 UTC, thibault-martinez approved these changes

2023-10-20 07:33 UTC, Alex6323 approved these changes

2023-10-20 09:40 UTC, Thoralf-M approved these changes

2023-10-20 10:45 UTC, merged