Python: SignedTransactionPayload changes
iotaledger/iota-sdk pull request #1553
Opened 2023-11-01 15:25 UTC by DaughterOfMars

# Description of change

Removes the transaction essence from python. Renames `TransactionPayload` and `Transaction`.

## Links to any relevant issues

Closes #1486

2023-11-01 17:01 UTC, thibault-martinez requested changes
Failing CI

2023-11-01 21:20 UTC, thibault-martinez requested changes
Failing CI

2023-11-02 15:56 UTC, thibault-martinez requested changes
Conflicts

2023-11-02 16:32 UTC, thibault-martinez commented on bindings/python/examples/how_tos/nft_collection/00_mint_issuer_nft.py
> +for outputIndex, output in enumerate(transaction["outputs"]):
Can we also remove `["outputs"]`?

2023-11-02 16:32 UTC, thibault-martinez commented on bindings/python/examples/how_tos/nft_collection/00_mint_issuer_nft.py
> +for outputIndex, output in enumerate(transaction["outputs"]):
I mean, use `.outputs` instead

2023-11-02 17:53 UTC, DaughterOfMars commented on bindings/python/examples/how_tos/nft_collection/00_mint_issuer_nft.py
> +for outputIndex, output in enumerate(transaction["outputs"]):
done

2023-11-03 08:56 UTC, thibault-martinez approved these changes

2023-11-03 08:59 UTC, Thoralf-M approved these changes

2023-11-03 09:01 UTC, Alex6323 approved these changes

2023-11-03 09:04 UTC, merged