Add prepare_claim_outputs()
iotaledger/iota-sdk pull request #1622
Opened 2023-11-15 13:52 UTC by tadzik

# Description of change

Implemented https://github.com/iotaledger/iota-sdk/issues/1569, adding `prepare_claim_outputs()` catching up with other `prepare_` methods.

## Links to any relevant issues

Fixes #1569

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

It has not! Do we have any tests for these? I see some examples, but I don't think they're meant to be runnable as-is.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2023-11-15 14:33 UTC, Thoralf-M commented on bindings/nodejs/lib/wallet/account.ts
>      async claimOutputs(outputIds: OutputId[]): Promise<Transaction> {
'outputIds' is defined but never used

2023-11-15 14:36 UTC, tadzik commented on bindings/nodejs/lib/wallet/account.ts
>      async claimOutputs(outputIds: OutputId[]): Promise<Transaction> {
Gah, caught in the act of not testing it.

2023-11-15 14:37 UTC, tadzik commented on bindings/nodejs/lib/wallet/account.ts
>      async claimOutputs(outputIds: OutputId[]): Promise<Transaction> {
Fixed in a7fc848fe

2023-11-15 14:37 UTC, Thoralf-M commented on bindings/python/iota_sdk/wallet/account.py
>          return Transaction.from_dict(self._call_account_method(
```suggestion
    def prepare_claim_outputs(
            self, output_ids_to_claim: List[OutputId]) -> PreparedTransaction:
        """Claim outputs.
        """
       return PreparedTransaction(self, self._call_account_method(
```
not sure if that's working or if the prepared data needs to be defined first

2023-11-15 14:38 UTC, Thoralf-M commented on bindings/nodejs/lib/wallet/account.ts
>              {
Can't comment there, but L264 and 265 also need to be changed

2023-11-16 10:27 UTC, tadzik commented on bindings/nodejs/lib/wallet/account.ts
>              {
Fixed in 64038538673b9422e07dd065e143a3d4f413afbc

2023-11-16 10:28 UTC, tadzik commented on bindings/python/iota_sdk/wallet/account.py
>          return Transaction.from_dict(self._call_account_method(
Yeah, that was indeed broken. Fixed in bd558d45dfdc1027854b7bc240b713f1dcc7ace4

2023-11-16 10:30 UTC, Thoralf-M commented on bindings/python/examples/how_tos/accounts_and_addresses/prepare_claim_outputs.py
I think I would remove it because there is already https://github.com/iotaledger/iota-sdk/blob/develop/bindings/python/examples/how_tos/advanced_transactions/claim_transaction.py

2023-11-16 10:31 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/advanced_transactions/prepare_claim_outputs.ts
Same for this, would also remove since there is already claim_outputs.ts

2023-11-16 14:26 UTC, Thoralf-M requested changes
Missing `Added` changelog entries in https://github.com/iotaledger/iota-sdk/blob/develop/sdk/CHANGELOG.md, https://github.com/iotaledger/iota-sdk/blob/develop/bindings/python/CHANGELOG.md and https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/CHANGELOG.md, apart from that looks good to me

2023-11-16 14:38 UTC, tadzik commented
> Missing `Added` changelog entries in https://github.com/iotaledger/iota-sdk/blob/develop/sdk/CHANGELOG.md, https://github.com/iotaledger/iota-sdk/blob/develop/bindings/python/CHANGELOG.md and https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/CHANGELOG.md, apart from that looks good to me

Added them in [b63cfc1](https://github.com/iotaledger/iota-sdk/pull/1622/commits/b63cfc1cff86628af8e18b577ae015116377a206). Hopefully I interpreted the patterns correctly :)

2023-11-16 14:38 UTC, Thoralf-M commented on bindings/nodejs/CHANGELOG.md
> +- `Account::prepare_claim_outputs()` method;
```suggestion
- `Account::prepareClaimOutputs()` method;
```

2023-11-16 15:02 UTC, Thoralf-M approved these changes

2023-11-16 15:05 UTC, DaughterOfMars approved these changes

2023-11-16 15:13 UTC, thibault-martinez approved these changes

2023-11-16 15:20 UTC, merged