Use bytes for Ed25519Signature public key
iotaledger/iota-sdk pull request #1818
Opened 2024-01-09 13:50 UTC by DaughterOfMars

# Description of change

Looks like using the `PublicKey` type here was a mistake, as the validation is not intended to be at the syntactic level. Unfortunately this is a breaking change, and there's no way to avoid that.

## Links to any relevant issues

https://github.com/iotaledger/inx-chronicle/issues/1308

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-01-09 14:17 UTC, Thoralf-M requested changes
Missing changelog entry and version update or don't you need a new release now?

2024-01-09 14:42 UTC, DaughterOfMars commented
Yeah, I figured I'd wait until we decide whether this is even happening 😆

2024-01-18 17:58 UTC, thibault-martinez commented on sdk/CHANGELOG.md
> +### Changed
There is a Deprecated section in the template so I'd use it

2024-01-18 17:58 UTC, thibault-martinez commented on bindings/core/src/method_handler/utils.rs
> +            use iota_sdk::types::block::Error;
Move to the other imports pls

2024-01-19 10:11 UTC, Alex6323 commented on sdk/src/types/block/signature/ed25519.rs
> +    /// Returns the public key of an [`Ed25519Signature`].
```suggestion
    /// Returns the unvalidated public key bytes of an [`Ed25519Signature`].
```

2024-01-19 13:35 UTC, Thoralf-M approved these changes

2024-01-19 14:25 UTC, Alex6323 approved these changes

2024-01-19 14:32 UTC, merged