Add output storage score tests
iotaledger/iota-sdk pull request #1827
Opened 2024-01-10 14:46 UTC by DaughterOfMars

# Description of change

Adds tests from the output TIPs as fixtures.

## Links to any relevant issues

Closes #1233

2024-01-10 14:49 UTC, Thoralf-M approved these changes

2024-01-10 15:13 UTC, Alex6323 approved these changes, later dismissed

2024-01-10 15:49 UTC, Thoralf-M requested changes
```
--- TRY 3 STDERR:        iota-sdk::mod types::storage_score::output_storage_score ---
thread 'types::storage_score::output_storage_score' panicked at sdk\tests\types\storage_score.rs:38:51:
called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum Output", line: 0, column: 0)
```

2024-01-10 15:52 UTC, thibault-martinez commented
> ```
> --- TRY 3 STDERR:        iota-sdk::mod types::storage_score::output_storage_score ---
> thread 'types::storage_score::output_storage_score' panicked at sdk\tests\types\storage_score.rs:38:51:
> called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum Output", line: 0, column: 0)
> ```

That's because we need to merge the MetadataFeature PR first

2024-01-17 17:06 UTC, Thoralf-M submitted a review, later dismissed

2024-01-17 17:13 UTC, thibault-martinez approved these changes

2024-01-17 18:40 UTC, Thoralf-M approved these changes

2024-01-17 18:40 UTC, merged