Add StateMetadataFeature
iotaledger/iota-sdk pull request #1849
Opened 2024-01-17 16:23 UTC by Thoralf-M

# Description of change

Add StateMetadataFeature

## Links to any relevant issues

Closes #1650 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

cargo test

2024-01-18 10:41 UTC, Alex6323 commented on sdk/src/types/block/output/feature/state_metadata.rs
Don't know if we want that but we could make the packable `verify..` methods generic over `T` and move them to `mod.rs` to re-use them.

2024-01-18 12:30 UTC, Thoralf-M commented on sdk/src/types/block/output/feature/state_metadata.rs
I also thought about it, but what would `T` be? Is it even possible to have something generic that can be used like this then `T::BYTE_LENGTH_RANGE` (in verify_byte_length_packable())?

2024-01-18 15:50 UTC, DaughterOfMars commented on sdk/src/types/block/output/feature/state_metadata.rs
tbh we already have lots of duplicated code, like between output types. I feel like we shouldn't stress too much about adding a little more for this

2024-01-18 16:55 UTC, Alex6323 commented on sdk/src/types/block/output/feature/state_metadata.rs
yeah, let's not get hung up on that

2024-01-18 16:56 UTC, Alex6323 submitted a review, later dismissed

2024-01-19 09:03 UTC, thibault-martinez commented on sdk/src/types/block/output/anchor.rs
> -    // pub fn state_metadata(&self) -> &[u8] {
I think a getter would still be useful tbh

2024-01-19 09:07 UTC, thibault-martinez requested changes

2024-01-19 09:07 UTC, thibault-martinez commented on sdk/src/types/block/output/feature/mod.rs
> +    StateMetadata(StateMetadataFeature),
You need to bump the type bytes of the features after this one

2024-01-19 09:11 UTC, thibault-martinez commented on sdk/src/types/block/output/feature/metadata.rs
```suggestion
```

2024-01-19 10:08 UTC, thibault-martinez commented on sdk/src/types/block/output/feature/mod.rs
> +    StateMetadata(StateMetadataFeature),
Oh that was already done, ignore me

2024-01-19 10:12 UTC, thibault-martinez commented on sdk/src/types/block/output/anchor.rs
> -    // pub fn state_metadata(&self) -> &[u8] {
But we don't really do it for the others so let's forget

2024-01-19 10:15 UTC, thibault-martinez commented on sdk/src/types/block/output/feature/state_metadata.rs
> +    impl Serialize for StateMetadataFeature {
```suggestion

    impl Serialize for StateMetadataFeature {
```

2024-01-19 10:47 UTC, thibault-martinez approved these changes

2024-01-19 12:48 UTC, DaughterOfMars approved these changes

2024-01-19 12:49 UTC, merged