Add mana balance to bindings types
iotaledger/iota-sdk pull request #1901
Opened 2024-01-29 13:55 UTC by DaughterOfMars

# Description of change

Add the new mana balance struct to the bindings.

2024-01-29 14:53 UTC, Thoralf-M submitted a review, later dismissed

2024-01-29 16:01 UTC, thibault-martinez requested changes
In the other PR you also changed the native tokens, you need to replicate in the bindings as well

2024-01-29 19:50 UTC, Thoralf-M approved these changes, later dismissed

2024-01-29 19:53 UTC, thibault-martinez approved these changes

2024-01-29 19:53 UTC, thibault-martinez requested changes
CI failing

2024-01-30 09:06 UTC, Thoralf-M approved these changes

2024-01-30 09:07 UTC, thibault-martinez approved these changes

2024-01-30 09:47 UTC, merged