Update RewardsParameters
iotaledger/iota-sdk pull request #2013
Opened 2024-02-16 17:06 UTC by thibault-martinez

Replicate https://github.com/iotaledger/iota.go/pull/691

2024-02-16 17:50 UTC, DaughterOfMars commented on bindings/nodejs/lib/types/models/info/node-info-protocol.ts
> +    reward_to_generation_ratio: number;
casing

2024-02-16 17:52 UTC, thibault-martinez commented on bindings/nodejs/lib/types/models/info/node-info-protocol.ts
> +    reward_to_generation_ratio: number;
fixed, thanks

2024-02-16 19:07 UTC, Thoralf-M commented on bindings/nodejs/lib/types/models/info/node-info-protocol.ts
> +    initialTargetRewards_rate: u64;
```suggestion
    initialTargetRewardsRate: u64;
```

2024-02-16 19:07 UTC, thibault-martinez commented on bindings/nodejs/lib/types/models/info/node-info-protocol.ts
> +    initialTargetRewards_rate: u64;
oh ffs

2024-02-16 19:10 UTC, Thoralf-M approved these changes, later dismissed

2024-02-16 21:22 UTC, DaughterOfMars requested changes
python unused imports

2024-02-17 04:17 UTC, DaughterOfMars approved these changes
We have an issue to update the tests once the TIPs are?

2024-02-19 07:26 UTC, Thoralf-M approved these changes

2024-02-19 07:27 UTC, merged