fix: listen function
iotaledger/iota-sdk pull request #227
Opened 2023-04-07 12:33 UTC by Tuditi

# Description of change

Fix the listen function

## Links to any relevant issues

closes: https://github.com/iotaledger/iota-sdk/issues/226

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Ran FF with the linked package.

Ran example 7-events.js (still fails due to a change introduced while merging sendAmount() & sendMicroAmount()

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-04-07 13:08 UTC, thibault-martinez requested changes
.change

2023-04-07 13:08 UTC, Thoralf-M commented
Is the wasm binding also working with this?

2023-04-07 13:15 UTC, Tuditi commented
> Is the wasm binding also working with this?

Not as far as I can see from this file:
https://github.com/iotaledger/iota-sdk/blob/6195e9a32edab969c0df858c507c1890b1f26320/sdk/src/wallet/bindings/wasm/lib/bindings.ts#L10

2023-04-07 13:31 UTC, thibault-martinez commented on .changes/fix-listen.md
> +"client-nodejs-binding": patch
```suggestion
"wallet-nodejs-binding": patch
```

2023-04-07 15:08 UTC, thibault-martinez approved these changes, later dismissed

2023-04-07 15:35 UTC, Thoralf-M commented
@Tuditi for the wasm binding the JS lib is copied over, apart from https://github.com/iotaledger/iota-sdk/blob/6195e9a32edab969c0df858c507c1890b1f26320/sdk/src/wallet/bindings/wasm/lib/bindings.ts
and there it still exports `listen`, so `listenTo` will not be found 
So I think the way this PR currently is would just change it around, so it's found on the nodejs binding, but will fail on wasm

2023-04-07 15:55 UTC, Thoralf-M commented
Maybe also enable the CI for wasm by adding `- "sdk/src/client/bindings/nodejs/**" # Re-include nodejs bindings, because lib is copied from there` here
https://github.com/iotaledger/iota-sdk/blob/d4c1d9a876cfc470d9ea6b290fc4f703f90178bf/.github/workflows/bindings-wasm.yml#L15-L28

2023-04-11 08:00 UTC, thibault-martinez submitted a review, later dismissed

2023-04-11 08:57 UTC, thibault-martinez approved these changes, later dismissed

2023-04-11 09:09 UTC, Thoralf-M commented on .github/workflows/bindings-wasm.yml
> +      - "sdk/src/wallet/bindings/nodejs/**" # Re-include node wallet bindings, b/c lib copied from there
```suggestion
      - "sdk/src/client/bindings/wasm/**" # Re-include wasm client bindings
      - "sdk/src/client/bindings/nodejs/**" # Re-include node client bindings, b/c lib copied from there
```

2023-04-11 09:09 UTC, Thoralf-M commented on .github/workflows/bindings-wasm.yml
> +      - "sdk/src/wallet/bindings/nodejs/**" # Re-include node wallet bindings, b/c lib copied from there
```suggestion
      - "sdk/src/client/bindings/wasm/**" # Re-include wasm client bindings
      - "sdk/src/client/bindings/nodejs/**" # Re-include node client bindings, b/c lib copied from there
```

2023-04-11 09:30 UTC, Thoralf-M approved these changes

2023-04-11 09:46 UTC, thibault-martinez approved these changes

2023-04-11 11:37 UTC, merged