Add voting power to balance
iotaledger/iota-sdk pull request #231
Opened 2023-04-10 14:39 UTC by thibault-martinez

2023-04-10 18:48 UTC, Thoralf-M commented on sdk/src/wallet/account/operations/balance.rs
> +                available: total_amount.saturating_sub(locked_amount).saturating_sub(voting_power),
```suggestion
                available: total_amount.saturating_sub(locked_amount+voting_power),
```

2023-04-10 19:38 UTC, thibault-martinez commented on sdk/src/wallet/account/operations/balance.rs
> +                available: total_amount.saturating_sub(locked_amount).saturating_sub(voting_power),
No risk of overflowing the addition? Should be fine I guess

2023-04-11 07:25 UTC, Thoralf-M commented on sdk/src/wallet/account/operations/balance.rs
> +                available: total_amount.saturating_sub(locked_amount).saturating_sub(voting_power),
There is probably a risk if there is a larger token supply

2023-04-11 07:25 UTC, Thoralf-M approved these changes, later dismissed

2023-04-11 08:05 UTC, Tuditi requested changes
Are you still planning to keep the `getVotingPower()` function then?

2023-04-11 08:05 UTC, Tuditi commented on sdk/src/wallet/bindings/nodejs/types/account.ts
> +    voting_power: string;
```suggestion
    votingPower: string;
```

2023-04-11 08:05 UTC, Tuditi commented on sdk/src/wallet/bindings/java/lib/src/main/java/org/iota/types/BaseCoinBalance.java
> +        return new BaseCoinBalance(total, available, voting_power);
Afaik camelCase is also the convention in Java.

2023-04-11 09:02 UTC, Thoralf-M submitted a review, later dismissed

2023-04-11 09:39 UTC, Thoralf-M approved these changes

2023-04-11 10:16 UTC, Tuditi approved these changes
Works fine in the nodejs examples! :fire:

2023-04-11 10:16 UTC, merged