OutputData::metadata is not a DTO anymore
iotaledger/iota-sdk pull request #364
Opened 2023-04-30 20:08 UTC by thibault-martinez

Closes https://github.com/iotaledger/iota-sdk/issues/356

2023-05-02 07:52 UTC, Thoralf-M requested changes
account_deserialization_incoming_transactions fails

2023-05-02 12:42 UTC, Alexandcoats approved these changes, later dismissed

2023-05-03 19:34 UTC, Alexandcoats submitted a review, later dismissed

2023-05-03 19:59 UTC, Thoralf-M approved these changes

2023-05-03 20:13 UTC, Alexandcoats approved these changes

2023-05-03 20:30 UTC, merged