Remove `ReceiptMilestoneOption`
iotaledger/iota-sdk pull request #375
Opened 2023-05-02 20:24 UTC by thibault-martinez

2023-05-03 08:46 UTC, Thoralf-M requested changes
Not removed from bindings

2023-05-03 13:04 UTC, Thoralf-M approved these changes

2023-05-03 14:30 UTC, Alexandcoats approved these changes

2023-05-04 11:11 UTC, qrayven approved these changes

2023-05-04 11:18 UTC, kwek20 approved these changes

2023-05-04 11:29 UTC, Alex6323 approved these changes

2023-05-04 11:30 UTC, merged