Feat/convert trait
iotaledger/iota-sdk pull request #526
Opened 2023-06-01 15:07 UTC by Alexandcoats

# Description of change

This replaces various `XLike` traits with a single unified `ConvertTo`.

## Links to any relevant issues
- Closes #522

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

2023-06-01 15:32 UTC, qrayven submitted a review, later dismissed

2023-06-02 09:06 UTC, thibault-martinez commented on sdk/src/types/mod.rs
> +pub mod convert;
This should probably be in `sdk/utils` instead?

2023-06-02 10:47 UTC, kwek20 commented on sdk/src/types/convert.rs
Should we implement like Rc, Box and Option here? Or leave for when we need it

2023-06-02 10:47 UTC, kwek20 commented on sdk/src/wallet/error.rs
> -impl From<Infallible> for Error {
💯

2023-06-02 11:09 UTC, kwek20 reviewed
idk im jsut thinking that maybe the trait should impl Into and TryInto, and we use those methods?

2023-06-02 18:20 UTC, Alexandcoats commented on sdk/src/types/convert.rs
Probably just wait until we need it.

2023-06-02 18:49 UTC, thibault-martinez requested changes
Changelog 😬

2023-06-02 19:25 UTC, thibault-martinez approved these changes

2023-06-05 07:25 UTC, qrayven approved these changes

2023-06-05 07:26 UTC, merged