Refactor some mqtt stuff and add tests
iotaledger/iota-sdk pull request #552
Opened 2023-06-06 17:32 UTC by Alexandcoats

# Description of change

Adds mqtt tests and refactors some stuff.

## Links to any relevant issues

- #387 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-06-06 17:42 UTC, thibault-martinez commented on sdk/src/client/node_api/mqtt/types.rs
> +    pub fn is_valid(&self) -> bool {
Since `new_unchecked` is private, should `is_valid` be public? We can't really publicly build an invalid Topic?

2023-06-06 18:09 UTC, Alexandcoats commented on sdk/src/client/node_api/mqtt/types.rs
> +    pub fn is_valid(&self) -> bool {
Fair point

2023-06-06 20:31 UTC, thibault-martinez approved these changes, later dismissed

2023-06-07 07:22 UTC, Thoralf-M approved these changes

2023-06-07 08:05 UTC, Thoralf-M requested changes
Test doesn't finish
TRY 1 SLOW [>1020.000s] iota-sdk::mod client::node_api::test_mqtt

2023-06-07 11:49 UTC, Thoralf-M approved these changes

2023-06-07 12:27 UTC, thibault-martinez approved these changes

2023-06-07 12:35 UTC, merged