Docs - Add Getting Started Section,
iotaledger/iota-sdk pull request #561
Opened 2023-06-07 13:36 UTC by lucas-tortora

# Description of change

* Added `Getting Started` sections for all languages
* Reduced introductory content by merging `Overview`  and `Welcome` into `About the IOTA SDK`
* Added document on testnet and test tokens

## Links to any relevant issues

fixes https://github.com/iotaledger/guild-devx/issues/104
fixes https://github.com/iotaledger/guild-devx/issues/99

## Type of change

- Documentation Fix
- Documentation Enhacement

## How the change has been tested

Wiki was built locally. 

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

2023-06-07 21:14 UTC, Dr-Electron requested changes

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/_admonitions/_warning_password_storage.md
> +In a production setup, do not store passwords in the host's environment variables or in the source code. See our backup and security recommendations for production setups.
Where are the "backup and security recommendations"?

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/static/img/iota_layers_overview.svg
I guess we need to update this one?
@thibault-martinez wdyt? Do you have anything in mind how this could/should look like. A quick sketch would be enough

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/about-the-iota-sdk.md
> +If you want to get involved in discussions about this library, or you're looking for support, go to the TODO channel
Will align with Antonio on it tomorrow. But I guess you can already replace it with `#iota-sdk` 🤔

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +On Windows, you will also need an LLVM. Our workflow uses
an LLVM? It's more a product name then a description 🤔 
```suggestion
On Windows, you will also need LLVM. Our workflow uses
```

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +an environment variable `RUSTFLAGS` to `-C target-feature=+crt-static`.
Should we recommend a way to install LLVM here?
Something like:
```suggestion
`https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/LLVM-11.0.1-win64.exe`. You may also need to set
an environment variable `RUSTFLAGS` to `-C target-feature=+crt-static`.

:::tip Install LLVM with Chocolatey

If you use [Chocolatey](https://chocolatey.org) you can install LLVM by executing `choco install llvm`

:::
```

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +    ```
Do both work? Do we want to promote both?
If so we should use tabs or [npm2yarn](https://docusaurus.io/docs/markdown-features/code-blocks#npm2yarn-remark-plugin)

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +    ```
Same here

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +```
You need to also install the example scripts with `yarn`first

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/python.mdx
> +    ```
Again: I prefer tabs ;)

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/rust.mdx
> +with [vcpkg](https://github.com/microsoft/vcpkg) or [chocolatey](https://chocolatey.org/).
Tabs? :trollface:

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/rust.mdx
> +```
We now use:
```suggestion
```bash
cargo run --release --all-features --example example_name
```
```
everywhere

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/rust.mdx
> +cargo run --example node_api_core_get_info --release
```suggestion
cargo run --release --all-features --example node_api_core_get_info
```

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/wasm.mdx
> +```
Again: Tabs or npm2yarn (:wen: merge :trollface: )

2023-06-07 21:14 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/wasm.mdx
> +```
Again you also need to install everything with `yarn`

2023-06-08 10:29 UTC, Thoralf-M commented on documentation/sdk/docs/about-the-iota-sdk.md
> +a [network for testing purposes (testnet)](https://wiki.iota.org/shimmer/develop/explanations/what-is-shimmer/networks/#public-testnet).   !["An overview of IOTA layers."](/img/iota_layers_overview.s
```suggestion
or a [network for testing purposes (testnet)](https://wiki.iota.org/shimmer/develop/explanations/what-is-shimmer/networks/#public-testnet). !["An overview of IOTA layers."](/img/iota_layers_overview.svg "An overview of IOTA layers.")
```

2023-06-08 10:38 UTC, Thoralf-M commented on documentation/sdk/docs/getting-started/rust.mdx
> +    .with_node('https://api.testnet.shimmer.network')? // Insert your node URL here
```suggestion
    .with_node("https://api.testnet.shimmer.network")? // Insert your node URL here
```

2023-06-08 10:41 UTC, Thoralf-M commented on documentation/sdk/docs/getting-started/rust.mdx
> +    wallet.store_mnemonic(mnemonic).await?;
```suggestion
    println!("Creating a wallet with mnemonic:\n'{mnemonic}'");
    wallet.store_mnemonic(mnemonic).await?;
```

2023-06-08 10:43 UTC, Thoralf-M commented on documentation/sdk/docs/getting-started/wasm.mdx
> +}
This should be TS/JS code

2023-06-08 13:17 UTC, lucas-tortora commented on documentation/sdk/docs/about-the-iota-sdk.md
> +If you want to get involved in discussions about this library, or you're looking for support, go to the TODO channel
```suggestion
If you want to get involved in discussions about this library, or you're looking for support, go to the `#iota-sdk` channel
```

2023-06-08 15:00 UTC, Thoralf-M commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +## Usage
Many things are basically the same as in the readme, can't we just import the section from the readme?

2023-06-08 15:18 UTC, lucas-tortora commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +## Usage
They are, and I think we will, but at this moment, we don't have the `codeSnippet` component readily available in external repositories to do this. 

There's a major restructuring coming up, which will probably allow us to import and trim and manipulate docs more freely. But, till we add the snippet component to the iota-wiki-cli, or go ahead with the restructure, the README contains a lot of information, and we can't use docusarus features such as tabs there. 

@Dr-Electron , do you know a way we could sort this out more efficiently?

2023-06-08 21:44 UTC, Dr-Electron commented on documentation/sdk/docs/about-the-iota-sdk.md
> +If you want to get involved in discussions about this library, or you're looking for support, go to the TODO channel
We decided on #libraries for now it seems 😅

2023-06-08 21:45 UTC, Dr-Electron commented on documentation/sdk/docs/getting-started/nodejs.mdx
> +## Usage
Not really. I would prefer doing the merge first. Everything else seems like a waste of time to me 🤔

2023-06-12 19:16 UTC, Thoralf-M approved these changes

2023-06-13 09:07 UTC, thibault-martinez approved these changes

2023-06-13 09:07 UTC, merged