Added create and destroy alias how-tos
iotaledger/iota-sdk pull request #686
Opened 2023-06-27 22:52 UTC by anistark

# Description of change

Added create and destroy alias how-tos

## Links to any relevant issues

Issue #413 

## How the change has been tested

Run the code example in how_tos

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-28 07:23 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/alias/create.ts
> +import { Utils, Wallet, initLogger } from '@iota/sdk';
'Utils' is defined but never used

2023-06-28 07:24 UTC, Thoralf-M reviewed
The .mdx docs will now only be added in the wiki repo?

2023-06-28 07:24 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/alias/destroy.ts
> +import { Utils, Wallet, initLogger } from '@iota/sdk';
'Utils' is defined but never used

2023-06-28 07:25 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/alias/destroy.ts
> -// In this example we will try to destroy the first alias there is in the account. This is only possible if possible
Why don't keep the description?

2023-06-28 07:27 UTC, Thoralf-M commented on bindings/python/examples/how_tos/alias/destroy.py
> +ALIAS_ID = "0x982667c59ade8ab8a99188f4de38c68b97fc2ca7ba28a1e9d8d683996247e152"
In the TS and Rust example we just get the first alias id from the balance

2023-06-28 07:28 UTC, Thoralf-M commented on bindings/python/examples/how_tos/alias/destroy.py
> +response = account.sync()
So something like this
```suggestion
balance = account.sync()

# We try to destroy the first alias in the account
alias_id = balance['foundries'][0]
```

2023-06-28 07:30 UTC, Thoralf-M commented on sdk/Cargo.toml
>  required-features = [ "wallet", "stronghold" ]
Please move it to the other how_tos/alias examples at L220

2023-07-04 14:59 UTC, thibault-martinez requested changes
Conflicts

2023-07-04 17:09 UTC, Thoralf-M commented on bindings/python/examples/how_tos/alias/destroy.py
> +alias_id = balance['foundries'][0]
```suggestion
alias_id = balance['aliases'][0]
```

2023-07-04 17:15 UTC, Thoralf-M requested changes
Remove the documentation folder again

2023-07-04 17:18 UTC, Thoralf-M commented on bindings/python/examples/how_tos/alias/create.py
> +print(f'Block sent: {os.environ["EXPLORER_URL"]}/block/{transaction["blockId"]}')
Should now work like this
```suggestion
print(f'Block sent: {os.environ["EXPLORER_URL"]}/block/{transaction.blockId}')
```

2023-07-04 17:18 UTC, Thoralf-M commented on bindings/python/examples/how_tos/alias/destroy.py
> +print(f'Block sent: {os.environ["EXPLORER_URL"]}/block/{transaction["blockId"]}')
```suggestion
print(f'Block sent: {os.environ["EXPLORER_URL"]}/block/{transaction.blockId}')
```

2023-07-04 17:18 UTC, Thoralf-M commented on sdk/Cargo.toml
> +required-features = [ "stronghold" ]
```suggestion
required-features = [ "wallet", "stronghold" ]
```

2023-07-04 17:19 UTC, Thoralf-M approved these changes

2023-07-05 09:56 UTC, thibault-martinez approved these changes

2023-07-05 09:57 UTC, merged