Feat: nft collection example for node
iotaledger/iota-sdk pull request #734
Opened 2023-07-06 17:02 UTC by kwek20

# Description of change

- Adds Nodejs nft collection example
- Updates structure

## Links to any relevant issues

fixes #597 

## Type of change

- Example

## How the change has been tested

Ran examples, same result in js and rust

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2023-07-06 18:41 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/nft_collection/00_mint_issuer_nft.ts
> +            `${process.env.ACCOUNT_ALIAS_1}`,
Didn't we remove this env var because it's more confusing? Should be just `'Alice'`

2023-07-06 18:41 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/nft_collection/00_mint_issuer_nft.ts
> +                if (
```suggestion
               // New minted NFT id is empty in the output
                if (
```

2023-07-06 18:42 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/nft_collection/01_mint_collection_nft.ts
> +            `${process.env.ACCOUNT_ALIAS_1}`,
Same here, just use `'Alice'`

2023-07-06 18:43 UTC, Thoralf-M commented on sdk/Cargo.toml
> +# NFT Examples
```suggestion
# NFT Collection Examples
```

2023-07-06 18:44 UTC, Thoralf-M commented on bindings/nodejs/examples/how_tos/nft_collection/01_mint_collection_nft.ts
> +const NFT_COLLECTION_SIZE = 10000;
You're crazy :carlos:
```suggestion
const NFT_COLLECTION_SIZE = 150;
```

2023-07-07 11:21 UTC, Thoralf-M requested changes
Conflict

2023-07-07 11:33 UTC, Thoralf-M approved these changes

2023-07-07 12:33 UTC, Alexandcoats approved these changes

2023-07-07 13:36 UTC, Alex6323 approved these changes

2023-07-07 14:15 UTC, merged