Move old nodejs bindings out of the SDK crate
iotaledger/iota-sdk pull request #778
Opened 2023-07-13 12:12 UTC by thibault-martinez

2023-07-13 12:57 UTC, Thoralf-M requested changes
.changes/config.json needs to be updated

2023-07-13 13:20 UTC, Thoralf-M approved these changes, later dismissed

2023-07-13 13:30 UTC, Alexandcoats submitted a review, later dismissed

2023-07-13 14:43 UTC, Thoralf-M approved these changes

2023-07-13 15:00 UTC, Alexandcoats commented
the nodejs bindings error is legitimate FYI

2023-07-14 07:58 UTC, Alex6323 approved these changes

2023-07-14 08:01 UTC, qrayven approved these changes

2023-07-14 08:05 UTC, merged