Prepare releases
iotaledger/iota-sdk pull request #827
Opened 2023-07-20 12:13 UTC by thibault-martinez

2023-07-20 12:14 UTC, Thoralf-M requested changes
Python is broken currently

2023-07-20 12:52 UTC, Thoralf-M approved these changes, later dismissed
Fine to merge this PR already, we should just wait with the python release until https://github.com/iotaledger/iota-sdk/pull/811 is merged

2023-07-21 09:54 UTC, kwek20 approved these changes

2023-07-21 09:55 UTC, Thoralf-M approved these changes

2023-07-21 10:06 UTC, merged