Small fixes to test and imports
iotaledger/iota-sdk pull request #857
Opened 2023-07-23 20:37 UTC by kwek20

residual from the `use_excess_if_low` pr

2023-07-23 20:54 UTC, Thoralf-M commented on sdk/tests/wallet/output_preparation.rs
>      // metadata feature
```suggestion
    // metadata and tag features
```

2023-07-23 20:54 UTC, Thoralf-M commented on sdk/tests/wallet/output_preparation.rs
>      // metadata feature
```suggestion
    // metadata and tag feature
```

2023-07-23 20:54 UTC, Thoralf-M commented on sdk/tests/wallet/output_preparation.rs
>      // metadata feature
```suggestion
    // metadata and tag feature
```

2023-07-23 20:55 UTC, Thoralf-M commented on sdk/tests/wallet/output_preparation.rs
>      // metadata feature
```suggestion
    // metadata and tag features
```

2023-07-24 08:04 UTC, Thoralf-M requested changes
tag feature requires additional storage deposit, so test need to be updated

2023-07-24 10:30 UTC, Thoralf-M requested changes
conflict

2023-07-24 10:54 UTC, Thoralf-M approved these changes

2023-07-24 11:37 UTC, thibault-martinez approved these changes

2023-07-24 11:37 UTC, merged