fix serialization
iotaledger/iota-sdk pull request #859
Opened 2023-07-23 21:13 UTC by abdulmth

# Description of change

Fix serialization of `TokenSchemeType`  for `Utils.computeTokenId` in node.js bindings.

## Links to any relevant issues

fixes #855 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

```
Utils.computeTokenId(
        "0x9be5f4577d6379f40f893c03453147bb0736f401c98b23059eb3f770421690f1",
        1,
        TokenSchemeType.Simple,
    );
```
outputs 
```
0x089be5f4577d6379f40f893c03453147bb0736f401c98b23059eb3f770421690f10400000000
``` 
instead of error.

2023-07-23 21:17 UTC, thibault-martinez submitted a review, later dismissed

2023-07-23 21:17 UTC, Thoralf-M requested changes
Changelog

2023-07-23 21:20 UTC, abdulmth commented
@Thoralf-M  should this be in the changelog? the API didn't change, it was an internal error 🤔

2023-07-23 21:22 UTC, Thoralf-M commented
@abdulmth I would say so, it was broken and is now fixed, independent of API change or not

2023-07-23 21:30 UTC, Thoralf-M approved these changes

2023-07-24 06:14 UTC, thibault-martinez approved these changes

2023-07-24 06:14 UTC, merged