return error on mismatch
iotaledger/iota-sdk pull request #946
Opened 2023-07-27 10:24 UTC by Alex6323

# Description of change

In some cases we just return an `Ok(())` on some stronghold related wallet methods even if the internally used secret manager is something else than a stronghold secret manager. This I think might be confusing to the user. This PR changes this behavior and will consistently return an error instead if a stronghold-only operation is tried to be called on some other secret manager.

## Links to any relevant issues

None

## Type of change

- Enhancement (a non-breaking change which adds functionality)

2023-07-27 20:09 UTC, thibault-martinez requested changes
Rebase

2023-07-28 07:47 UTC, Thoralf-M submitted a review, later dismissed

2023-07-28 08:17 UTC, thibault-martinez requested changes
Changelog

2023-07-28 12:25 UTC, Alexandcoats approved these changes, later dismissed

2023-07-29 09:28 UTC, Thoralf-M approved these changes

2023-07-29 10:06 UTC, thibault-martinez approved these changes

2023-07-29 10:06 UTC, merged