Feat/cli: added mnemonic gen from console only
iotaledger/iota-sdk pull request #983
Opened 2023-08-01 12:20 UTC by kwek20

# Description of change

Allows getting mnemonic through just command line args

## Links to any relevant issues

fixes [#652](https://github.com/iotaledger/iota-sdk/issues/652)

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Test cases:
- `./wallet mnemonic --output-stdout no` -> Write to default file **DO WE WANT THIS OR BACK TO USER CHOICE**
- `./wallet mnemonic --output-stdout yes` -> Write to console
- `./wallet mnemonic --output-stdout` -> Write to console
- `./wallet mnemonic --output-stdout` -> Write to console
- `./wallet mnemonic --output-file-name filename.txt` -> Writes to file
- `./wallet mnemonic --output-file-name filename.txt --output-stdout` -> Writes to file and console
- `./wallet mnemonic` -> Prompts user

2023-08-01 12:25 UTC, thibault-martinez commented
Not 2.0?

2023-08-01 12:34 UTC, kwek20 commented
oh :D
didnt even realize

2023-08-01 12:54 UTC, DaughterOfMars commented on cli/src/command/wallet.rs
> +        #[arg(long, num_args = 0..2, default_missing_value = Some("true"), value_parser = BoolishValueParser::new())]
Does this still allow using the flag without args, like so?
``` cli --output-stdout ```

2023-08-01 12:57 UTC, DaughterOfMars commented on cli/src/helper.rs
> +        (None, None) => {
shouldn't this match `(None, Some(false))` too?

2023-08-01 12:59 UTC, kwek20 commented on cli/src/command/wallet.rs
> +        #[arg(long, num_args = 0..2, default_missing_value = Some("true"), value_parser = BoolishValueParser::new())]
yes, its one of the test cases i did, the 0 num args allows this if there is a default

2023-08-01 12:59 UTC, kwek20 commented on cli/src/helper.rs
> +        (None, None) => {
I chose not to, as when you provide no to console, then the user picking section still allows picking console, kinda weird.
But i left the question open in test case 1

2023-08-01 13:00 UTC, Alexandcoats commented on cli/src/command/wallet.rs
> +        #[arg(long, num_args = 0..2, default_missing_value = Some("true"), value_parser = BoolishValueParser::new())]
What about the other instance above then?

2023-08-01 13:00 UTC, Alexandcoats commented on cli/src/command/wallet.rs
> +        #[arg(long, num_args = 0..2, default_missing_value = Some("true"), value_parser = BoolishValueParser::new())]
Also can you use `0..=1` instead? This range is a little less clear to read

2023-08-01 13:10 UTC, thibault-martinez requested changes
Changelog

2023-08-01 13:11 UTC, Alexandcoats commented on cli/src/helper.rs
> +        (None, None) => {
Yeah, it is weird but it also doesn't really make sense to write to file when the user doesn't specify they want to

2023-08-01 13:13 UTC, kwek20 commented on cli/src/helper.rs
> +        (None, None) => {
lets see what the others think

2023-08-01 13:13 UTC, kwek20 commented on cli/src/command/wallet.rs
> +        #[arg(long, num_args = 0..2, default_missing_value = Some("true"), value_parser = BoolishValueParser::new())]
ah yea that works better

2023-08-02 12:09 UTC, Thoralf-M submitted a review, later dismissed
I'm fine with this, will also approve again if you change the match to `(None, Some(false))`

2023-08-02 13:05 UTC, Thoralf-M approved these changes

2023-08-02 13:53 UTC, Alexandcoats approved these changes

2023-08-04 14:27 UTC, merged