fix: Prevent webpack loading bindings when importing UTXOInput type
iotaledger/iota-sdk pull request #990
Opened 2023-08-03 12:53 UTC by msarcev

# Description of change

- Reimplemented `fromOutputId` static function without going through callUtilsMethod.

Prevents webpack loading bindings when importing UTXOInput type.

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #issue_number`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Tested the static function manually with some outputId cases.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-08-03 14:04 UTC, Alexandcoats requested changes
I don't think this is the right approach

2023-08-04 09:11 UTC, Thoralf-M approved these changes

2023-08-04 12:06 UTC, Alexandcoats approved these changes
I think this is okay?

2023-08-08 08:16 UTC, qrayven commented
> I think this is okay?

I think It's ok because this is technically the only place we import `bindings` in `types`, so we won't need similar fixes for other types.

2023-08-08 08:16 UTC, qrayven approved these changes

2023-08-08 10:03 UTC, abdulmth approved these changes

2023-08-08 12:15 UTC, merged